---
abstract: 'Generate Kwalitee ratings for a distribution'
author:
  - 'Thomas Klausner <domm@cpan.org>'
  - 'Kenichi Ishigaki <ishigaki@cpan.org>'
build_requires:
  Cwd: '0'
  ExtUtils::MakeMaker: '0'
  Test::Deep: '0'
  Test::More: '0'
  Test::NoWarnings: '0'
  Test::Warn: '0.11'
configure_requires:
  ExtUtils::MakeMaker::CPANfile: '0.06'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.76, CPAN::Meta::Converter version 2.140640'
keywords:
  - CPANTS
  - kwalitee
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Module-CPANTS-Analyse
no_index:
  directory:
    - t
    - inc
requires:
  Archive::Any::Lite: '0.06'
  Archive::Tar: '1.48'
  Array::Diff: '0.04'
  CPAN::DistnameInfo: '0.06'
  CPAN::Meta::Validator: '2.133380'
  CPAN::Meta::YAML: '0.008'
  Class::Accessor: '0.19'
  IO::Capture: '0.05'
  Module::ExtractUse: '0.33'
  Module::Pluggable: '2.96'
  Set::Scalar: '0'
  Software::License: '0.103008'
  Software::License::CC_BY_SA_3_0: '0'
  Text::Balanced: '0'
  version: '0.73'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Module-CPANTS-Analyse
  homepage: http://cpants.cpanauthors.org
  repository: https://github.com/cpants/Module-CPANTS-Analyse
version: 0.93_01
