---
abstract: 'Generate Kwalitee ratings for a distribution'
author:
  - 'Lars Dɪᴇᴄᴋᴏᴡ <daxim@cpan.org>'
build_requires:
  Cwd: 0
  Test::Deep: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Warn: 0.11
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120630'
keywords:
  - CPANTS
  - kwalitee
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-CPANTS-Analyse
provides:
  Module::CPANTS::Analyse:
    file: lib/Module/CPANTS/Analyse.pm
    version: 0.87
  Module::CPANTS::Kwalitee:
    file: lib/Module/CPANTS/Kwalitee.pm
    version: 0.87
  Module::CPANTS::Kwalitee::BrokenInstaller:
    file: lib/Module/CPANTS/Kwalitee/BrokenInstaller.pm
    version: 0.87
  Module::CPANTS::Kwalitee::CpantsErrors:
    file: lib/Module/CPANTS/Kwalitee/CpantsErrors.pm
    version: 0.87
  Module::CPANTS::Kwalitee::Distname:
    file: lib/Module/CPANTS/Kwalitee/Distname.pm
    version: 0.87
  Module::CPANTS::Kwalitee::Distros:
    file: lib/Module/CPANTS/Kwalitee/Distros.pm
    version: 0.87
  Module::CPANTS::Kwalitee::Files:
    file: lib/Module/CPANTS/Kwalitee/Files.pm
    version: 0.87
  Module::CPANTS::Kwalitee::FindModules:
    file: lib/Module/CPANTS/Kwalitee/FindModules.pm
    version: 0.87
  Module::CPANTS::Kwalitee::License:
    file: lib/Module/CPANTS/Kwalitee/License.pm
    version: 0.87
  Module::CPANTS::Kwalitee::Manifest:
    file: lib/Module/CPANTS/Kwalitee/Manifest.pm
    version: 0.87
  Module::CPANTS::Kwalitee::MetaYML:
    file: lib/Module/CPANTS/Kwalitee/MetaYML.pm
    version: 0.87
  Module::CPANTS::Kwalitee::NeedsCompiler:
    file: lib/Module/CPANTS/Kwalitee/NeedsCompiler.pm
    version: 0.87
  Module::CPANTS::Kwalitee::Pod:
    file: lib/Module/CPANTS/Kwalitee/Pod.pm
    version: 0.87
  Module::CPANTS::Kwalitee::Prereq:
    file: lib/Module/CPANTS/Kwalitee/Prereq.pm
    version: 0.87
  Module::CPANTS::Kwalitee::Repackageable:
    file: lib/Module/CPANTS/Kwalitee/Repackageable.pm
    version: 0.87
  Module::CPANTS::Kwalitee::Signature:
    file: lib/Module/CPANTS/Kwalitee/Signature.pm
    version: 0.87
  Module::CPANTS::Kwalitee::Uses:
    file: lib/Module/CPANTS/Kwalitee/Uses.pm
    version: 0.87
  Module::CPANTS::Kwalitee::Version:
    file: lib/Module/CPANTS/Kwalitee/Version.pm
    version: 0.87
requires:
  Archive::Any: 0.06
  Archive::Tar: 1.48
  Array::Diff: 0.04
  CPAN::DistnameInfo: 0.06
  Class::Accessor: 0.19
  ExtUtils::Manifest: 0
  File::Find::Rule: 0
  File::Slurp: 0
  File::chdir: 0
  IO::Capture: 0.05
  LWP::Simple: 0
  List::MoreUtils: 0
  Module::ExtractUse: 0.24
  Module::Pluggable: 2.96
  Module::Signature: 0
  Pod::Simple::Checker: 2.02
  Readonly: 0
  Set::Scalar: 0
  Software::License: 0.003
  Test::CPAN::Meta::YAML::Version: 0.21
  Text::CSV_XS: 0.45
  YAML::Any: 0
  perl: 5.006
  version: 0.73
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Module-CPANTS-Analyse
  homepage: http://cpants.perl.org
  license: http://dev.perl.org/licenses/
  repository: https://github.com/daxim/Module-CPANTS-Analyse
version: 0.87
